import caffeLatteImg from "./images/caffe-latte.jpg";
import cappuccinoImg from "./images/cappuccino.jpg";
import flatWhiteImg from "./images/flat-white.jpg";
import americanoImg from "./images/americano.jpg";
import espressoImg from "./images/espresso.jpg";
import doppioImg from "./images/doppio.jpg";
import macchiatoImg from "./images/macchiato.jpg";
import cortadoImg from "./images/cortado.jpg";
import mochaImg from "./images/mocha.jpg";
import caramelMacchiatoImg from "./images/caramel-macchiato.jpg";
import vanillaLatteImg from "./images/vanilla-latte.jpg";
import hazelnutLatteImg from "./images/hazelnut-latte.jpg";
import spanishLatteImg from "./images/spanish-latte.jpg";
import hotChocolateImg from "./images/hot-chocolate.jpg";
import chaiLatteImg from "./images/chai-latte.jpg";
import matchaLatteImg from "./images/matcha-latte.jpg";
import turkishCoffeeImg from "./images/turkish-coffee.jpg";
import pourOverImg from "./images/pour-over.jpg";
import icedLatteImg from "./images/iced-latte.jpg";
import icedAmericanoImg from "./images/iced-americano.jpg";
import coldBrewImg from "./images/cold-brew.jpg";
import nitroColdBrewImg from "./images/nitro-cold-brew.jpg";
import vanillaColdBrewImg from "./images/vanilla-cold-brew.jpg";
import icedMochaImg from "./images/iced-mocha.jpg";
import icedCaramelMacchiatoImg from "./images/iced-caramel-macchiato.jpg";
import icedSpanishLatteImg from "./images/iced-spanish-latte.jpg";
import icedMatchaLatteImg from "./images/iced-matcha-latte.jpg";
import icedChaiLatteImg from "./images/iced-chai-latte.jpg";
import espressoTonicImg from "./images/espresso-tonic.jpg";
import mochaFrappeImg from "./images/mocha-frappe.jpg";
import affogatoImg from "./images/affogato.jpg";
import peachIcedTeaImg from "./images/peach-iced-tea.jpg";
import mintLemonadeImg from "./images/mint-lemonade.jpg";
import freshOrangeJuiceImg from "./images/fresh-orange-juice.jpg";
import strawberrySmoothieImg from "./images/strawberry-smoothie.jpg";
import mangoSmoothieImg from "./images/mango-smoothie.jpg";
import sparklingWaterImg from "./images/sparkling-water.jpg";
import butterCroissantImg from "./images/butter-croissant.jpg";
import chocolateCroissantImg from "./images/chocolate-croissant.jpg";
import almondCroissantImg from "./images/almond-croissant.jpg";
import pistachioCroissantImg from "./images/pistachio-croissant.jpg";
import painSuisseImg from "./images/pain-suisse.jpg";
import cinnamonRollImg from "./images/cinnamon-roll.jpg";
import blueberryMuffinImg from "./images/blueberry-muffin.jpg";
import chocolateMuffinImg from "./images/chocolate-muffin.jpg";
import bananaBreadImg from "./images/banana-bread.jpg";
import blueberrySconeImg from "./images/blueberry-scone.jpg";
import danishPastryImg from "./images/danish-pastry.jpg";
import appleTurnoverImg from "./images/apple-turnover.jpg";
import cheeseDanishImg from "./images/cheese-danish.jpg";
import bagelAndCreamCheeseImg from "./images/bagel-and-cream-cheese.jpg";
import softPretzelImg from "./images/soft-pretzel.jpg";
import baklavaImg from "./images/baklava.jpg";
import chocolateChipCookieImg from "./images/chocolate-chip-cookie.jpg";
import macaronImg from "./images/macaron.jpg";
import classicCheesecakeImg from "./images/classic-cheesecake.jpg";
import lotusCheesecakeImg from "./images/lotus-cheesecake.jpg";
import chocolateCakeImg from "./images/chocolate-cake.jpg";
import redVelvetCakeImg from "./images/red-velvet-cake.jpg";
import carrotCakeImg from "./images/carrot-cake.jpg";
import tiramisuImg from "./images/tiramisu.jpg";
import brownieImg from "./images/brownie.jpg";
import walnutBlondieImg from "./images/walnut-blondie.jpg";
import chocolateLavaCakeImg from "./images/chocolate-lava-cake.jpg";
import cremeBruleeImg from "./images/creme-brulee.jpg";
import pannaCottaImg from "./images/panna-cotta.jpg";
import miniPancakesImg from "./images/mini-pancakes.jpg";
import belgianWaffleImg from "./images/belgian-waffle.jpg";
import applePieImg from "./images/apple-pie.jpg";
import pecanPieImg from "./images/pecan-pie.jpg";
import banoffeePieImg from "./images/banoffee-pie.jpg";
import chocolateEclairImg from "./images/chocolate-eclair.jpg";
import iceCreamSundaeImg from "./images/ice-cream-sundae.jpg";

import type { menuItem } from "@/model/menu-item.model";

export const MENUITEMS: menuItem[] = [
    // HOT DRINKS
    {
        id: "caffe-latte",
        name: "Caffè Latte",
        description: "Double espresso with steamed milk and a thin veil of foam.",
        price: 18,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: true,
        image: caffeLatteImg,
    },
    {
        id: "cappuccino",
        name: "Cappuccino",
        description: "Equal parts espresso, milk and dense velvety foam.",
        price: 19,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: true,
        image: cappuccinoImg,
    },
    {
        id: "flat-white",
        name: "Flat White",
        description: "Ristretto shots under silky microfoam. No foam cap.",
        price: 20,
        category: "hot-drinks",
        isAvailable: false,
        isPopular: false,
        image: flatWhiteImg,
    },
    {
        id: "americano",
        name: "Americano",
        description: "Espresso lengthened with hot water for a clean finish.",
        price: 16,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: americanoImg,
    },
    {
        id: "espresso",
        name: "Espresso",
        description: "A single 25ml shot pulled from our house blend.",
        price: 14,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: true,
        image: espressoImg,
    },
    {
        id: "doppio",
        name: "Doppio",
        description: "Two espresso shots, no water, no milk.",
        price: 17,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: doppioImg,
    },
    {
        id: "macchiato",
        name: "Macchiato",
        description: "Espresso marked with a spoonful of steamed milk.",
        price: 17,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: macchiatoImg,
    },
    {
        id: "cortado",
        name: "Cortado",
        description: "Espresso cut with warm milk in a 1:1 ratio.",
        price: 19,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: cortadoImg,
    },
    {
        id: "mocha",
        name: "Mocha",
        description: "Espresso, dark chocolate and steamed milk.",
        price: 22,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: true,
        image: mochaImg,
    },
    {
        id: "caramel-macchiato",
        name: "Caramel Macchiato",
        description: "Vanilla milk, espresso and a caramel drizzle.",
        price: 24,
        category: "hot-drinks",
        isAvailable: false,
        isPopular: true,
        image: caramelMacchiatoImg,
    },
    {
        id: "vanilla-latte",
        name: "Vanilla Latte",
        description: "Latte sweetened with Madagascar vanilla syrup.",
        price: 22,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: vanillaLatteImg,
    },
    {
        id: "hazelnut-latte",
        name: "Hazelnut Latte",
        description: "Roasted hazelnut syrup folded into steamed milk.",
        price: 23,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: hazelnutLatteImg,
    },
    {
        id: "spanish-latte",
        name: "Spanish Latte",
        description: "Condensed milk latte, sweet and full bodied.",
        price: 23,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: true,
        image: spanishLatteImg,
    },
    {
        id: "hot-chocolate",
        name: "Hot Chocolate",
        description: "Melted 70% chocolate stirred into hot milk.",
        price: 21,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: hotChocolateImg,
    },
    {
        id: "chai-latte",
        name: "Chai Latte",
        description: "Black tea brewed with cardamom, clove and ginger.",
        price: 20,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: chaiLatteImg,
    },
    {
        id: "matcha-latte",
        name: "Matcha Latte",
        description: "Ceremonial grade matcha whisked with steamed milk.",
        price: 24,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: true,
        image: matchaLatteImg,
    },
    {
        id: "turkish-coffee",
        name: "Turkish Coffee",
        description: "Finely ground beans simmered in a copper cezve.",
        price: 18,
        category: "hot-drinks",
        isAvailable: false,
        isPopular: false,
        image: turkishCoffeeImg,
    },
    {
        id: "pour-over",
        name: "Pour Over",
        description: "Single origin, hand poured over a V60 filter.",
        price: 21,
        category: "hot-drinks",
        isAvailable: true,
        isPopular: false,
        image: pourOverImg,
    },

    // COLD DRINKS
    {
        id: "iced-latte",
        name: "Iced Latte",
        description: "Espresso over cold milk and ice.",
        price: 22,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: true,
        image: icedLatteImg,
    },
    {
        id: "iced-americano",
        name: "Iced Americano",
        description: "Espresso poured over iced water. Bright and clean.",
        price: 18,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: icedAmericanoImg,
    },
    {
        id: "cold-brew",
        name: "Cold Brew",
        description: "Steeped 18 hours for low acidity and deep body.",
        price: 21,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: true,
        image: coldBrewImg,
    },
    {
        id: "nitro-cold-brew",
        name: "Nitro Cold Brew",
        description: "Cold brew charged with nitrogen for a cascading head.",
        price: 26,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: true,
        image: nitroColdBrewImg,
    },
    {
        id: "vanilla-cold-brew",
        name: "Vanilla Cold Brew",
        description: "Cold brew topped with vanilla sweet cream.",
        price: 24,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: vanillaColdBrewImg,
    },
    {
        id: "iced-mocha",
        name: "Iced Mocha",
        description: "Chocolate, espresso and cold milk over ice.",
        price: 25,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: icedMochaImg,
    },
    {
        id: "iced-caramel-macchiato",
        name: "Iced Caramel Macchiato",
        description: "Layered vanilla milk, ice, espresso and caramel.",
        price: 26,
        category: "cold-drinks",
        isAvailable: false,
        isPopular: true,
        image: icedCaramelMacchiatoImg,
    },
    {
        id: "iced-spanish-latte",
        name: "Iced Spanish Latte",
        description: "Condensed milk and espresso over crushed ice.",
        price: 27,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: icedSpanishLatteImg,
    },
    {
        id: "iced-matcha-latte",
        name: "Iced Matcha Latte",
        description: "Cold matcha layered over chilled milk.",
        price: 26,
        category: "cold-drinks",
        isAvailable: false,
        isPopular: true,
        image: icedMatchaLatteImg,
    },
    {
        id: "iced-chai-latte",
        name: "Iced Chai Latte",
        description: "Spiced chai concentrate shaken with cold milk.",
        price: 24,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: icedChaiLatteImg,
    },
    {
        id: "espresso-tonic",
        name: "Espresso Tonic",
        description: "Tonic water, ice and a citrus-forward espresso.",
        price: 25,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: espressoTonicImg,
    },
    {
        id: "mocha-frappe",
        name: "Mocha Frappe",
        description: "Blended ice, chocolate and espresso, whipped cream on top.",
        price: 28,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: true,
        image: mochaFrappeImg,
    },
    {
        id: "affogato",
        name: "Affogato",
        description: "Vanilla gelato drowned in a fresh espresso shot.",
        price: 26,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: affogatoImg,
    },
    {
        id: "peach-iced-tea",
        name: "Peach Iced Tea",
        description: "Black tea, white peach and a squeeze of lemon.",
        price: 18,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: peachIcedTeaImg,
    },
    {
        id: "mint-lemonade",
        name: "Mint Lemonade",
        description: "Pressed lemon, fresh mint and crushed ice.",
        price: 19,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: mintLemonadeImg,
    },
    {
        id: "fresh-orange-juice",
        name: "Fresh Orange Juice",
        description: "Squeezed to order. Nothing added.",
        price: 20,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: freshOrangeJuiceImg,
    },
    {
        id: "strawberry-smoothie",
        name: "Strawberry Smoothie",
        description: "Strawberries blended with yoghurt and honey.",
        price: 28,
        category: "cold-drinks",
        isAvailable: false,
        isPopular: false,
        image: strawberrySmoothieImg,
    },
    {
        id: "mango-smoothie",
        name: "Mango Smoothie",
        description: "Alphonso mango, lime and a touch of coconut milk.",
        price: 28,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: mangoSmoothieImg,
    },
    {
        id: "sparkling-water",
        name: "Sparkling Water",
        description: "Chilled sparkling mineral water with lemon.",
        price: 12,
        category: "cold-drinks",
        isAvailable: true,
        isPopular: false,
        image: sparklingWaterImg,
    },

    // PASTRIES
    {
        id: "butter-croissant",
        name: "Butter Croissant",
        description: "Laminated over three days with French butter.",
        price: 14,
        category: "pastries",
        isAvailable: true,
        isPopular: true,
        image: butterCroissantImg,
    },
    {
        id: "chocolate-croissant",
        name: "Chocolate Croissant",
        description: "Two batons of dark chocolate in flaky layers.",
        price: 18,
        category: "pastries",
        isAvailable: true,
        isPopular: true,
        image: chocolateCroissantImg,
    },
    {
        id: "almond-croissant",
        name: "Almond Croissant",
        description: "Filled with frangipane, topped with toasted almonds.",
        price: 20,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: almondCroissantImg,
    },
    {
        id: "pistachio-croissant",
        name: "Pistachio Croissant",
        description: "Sicilian pistachio cream, crushed pistachio crust.",
        price: 21,
        category: "pastries",
        isAvailable: false,
        isPopular: true,
        image: pistachioCroissantImg,
    },
    {
        id: "pain-suisse",
        name: "Pain Suisse",
        description: "Brioche dough with vanilla custard and chocolate chips.",
        price: 19,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: painSuisseImg,
    },
    {
        id: "cinnamon-roll",
        name: "Cinnamon Roll",
        description: "Soft coil of cinnamon sugar under cream cheese glaze.",
        price: 16,
        category: "pastries",
        isAvailable: true,
        isPopular: true,
        image: cinnamonRollImg,
    },
    {
        id: "blueberry-muffin",
        name: "Blueberry Muffin",
        description: "Packed with wild blueberries and a sugar crust.",
        price: 15,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: blueberryMuffinImg,
    },
    {
        id: "chocolate-muffin",
        name: "Chocolate Muffin",
        description: "Cocoa sponge studded with chocolate chunks.",
        price: 16,
        category: "pastries",
        isAvailable: false,
        isPopular: false,
        image: chocolateMuffinImg,
    },
    {
        id: "banana-bread",
        name: "Banana Bread",
        description: "Ripe banana loaf with walnuts. Served warm.",
        price: 15,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: bananaBreadImg,
    },
    {
        id: "blueberry-scone",
        name: "Blueberry Scone",
        description: "Crumbly scone with blueberries and clotted cream.",
        price: 14,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: blueberrySconeImg,
    },
    {
        id: "danish-pastry",
        name: "Danish Pastry",
        description: "Buttery pastry with seasonal fruit and custard.",
        price: 17,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: danishPastryImg,
    },
    {
        id: "apple-turnover",
        name: "Apple Turnover",
        description: "Spiced apple sealed in puff pastry.",
        price: 18,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: appleTurnoverImg,
    },
    {
        id: "cheese-danish",
        name: "Cheese Danish",
        description: "Sweet cream cheese baked into a golden shell.",
        price: 18,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: cheeseDanishImg,
    },
    {
        id: "bagel-and-cream-cheese",
        name: "Bagel & Cream Cheese",
        description: "Boiled-then-baked bagel with whipped cream cheese.",
        price: 20,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: bagelAndCreamCheeseImg,
    },
    {
        id: "soft-pretzel",
        name: "Soft Pretzel",
        description: "Hand-twisted, salted, baked to order.",
        price: 13,
        category: "pastries",
        isAvailable: false,
        isPopular: false,
        image: softPretzelImg,
    },
    {
        id: "baklava",
        name: "Baklava",
        description: "Filo, pistachio and honey syrup. Cut fresh daily.",
        price: 22,
        category: "pastries",
        isAvailable: true,
        isPopular: true,
        image: baklavaImg,
    },
    {
        id: "chocolate-chip-cookie",
        name: "Chocolate Chip Cookie",
        description: "Brown butter dough, sea salt, molten centre.",
        price: 12,
        category: "pastries",
        isAvailable: true,
        isPopular: true,
        image: chocolateChipCookieImg,
    },
    {
        id: "macaron",
        name: "Macaron",
        description: "Almond shells with ganache. Ask for today's flavours.",
        price: 14,
        category: "pastries",
        isAvailable: true,
        isPopular: false,
        image: macaronImg,
    },

    // DESSERTS
    {
        id: "classic-cheesecake",
        name: "Classic Cheesecake",
        description: "New York style on a buttered biscuit base.",
        price: 24,
        category: "desserts",
        isAvailable: true,
        isPopular: true,
        image: classicCheesecakeImg,
    },
    {
        id: "lotus-cheesecake",
        name: "Lotus Cheesecake",
        description: "Caramelised biscuit base, spread and crumb.",
        price: 29,
        category: "desserts",
        isAvailable: true,
        isPopular: true,
        image: lotusCheesecakeImg,
    },
    {
        id: "chocolate-cake",
        name: "Chocolate Cake",
        description: "Four layers of sponge and dark chocolate ganache.",
        price: 26,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: chocolateCakeImg,
    },
    {
        id: "red-velvet-cake",
        name: "Red Velvet Cake",
        description: "Cocoa sponge with cream cheese frosting.",
        price: 28,
        category: "desserts",
        isAvailable: true,
        isPopular: true,
        image: redVelvetCakeImg,
    },
    {
        id: "carrot-cake",
        name: "Carrot Cake",
        description: "Spiced carrot and walnut with citrus frosting.",
        price: 25,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: carrotCakeImg,
    },
    {
        id: "tiramisu",
        name: "Tiramisu",
        description: "Savoiardi soaked in espresso, mascarpone, cocoa.",
        price: 27,
        category: "desserts",
        isAvailable: false,
        isPopular: true,
        image: tiramisuImg,
    },
    {
        id: "brownie",
        name: "Brownie",
        description: "Fudgy centre, crackled top, 70% chocolate.",
        price: 18,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: brownieImg,
    },
    {
        id: "walnut-blondie",
        name: "Walnut Blondie",
        description: "White chocolate and toasted walnut blondie.",
        price: 20,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: walnutBlondieImg,
    },
    {
        id: "chocolate-lava-cake",
        name: "Chocolate Lava Cake",
        description: "Warm molten centre with vanilla ice cream.",
        price: 32,
        category: "desserts",
        isAvailable: true,
        isPopular: true,
        image: chocolateLavaCakeImg,
    },
    {
        id: "creme-brulee",
        name: "Crème Brûlée",
        description: "Vanilla custard under a torched sugar crust.",
        price: 30,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: cremeBruleeImg,
    },
    {
        id: "panna-cotta",
        name: "Panna Cotta",
        description: "Set cream with berry coulis.",
        price: 26,
        category: "desserts",
        isAvailable: false,
        isPopular: false,
        image: pannaCottaImg,
    },
    {
        id: "mini-pancakes",
        name: "Mini Pancakes",
        description: "A dozen silver dollar pancakes with maple butter.",
        price: 23,
        category: "desserts",
        isAvailable: true,
        isPopular: true,
        image: miniPancakesImg,
    },
    {
        id: "belgian-waffle",
        name: "Belgian Waffle",
        description: "Pearl sugar waffle with berries and cream.",
        price: 29,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: belgianWaffleImg,
    },
    {
        id: "apple-pie",
        name: "Apple Pie",
        description: "Lattice crust, cinnamon apples, served warm.",
        price: 24,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: applePieImg,
    },
    {
        id: "pecan-pie",
        name: "Pecan Pie",
        description: "Toasted pecans set in bourbon caramel.",
        price: 26,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: pecanPieImg,
    },
    {
        id: "banoffee-pie",
        name: "Banoffee Pie",
        description: "Banana, dulce de leche and whipped cream.",
        price: 28,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: banoffeePieImg,
    },
    {
        id: "chocolate-eclair",
        name: "Chocolate Éclair",
        description: "Choux filled with crème pâtissière, chocolate fondant.",
        price: 19,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: chocolateEclairImg,
    },
    {
        id: "ice-cream-sundae",
        name: "Ice Cream Sundae",
        description: "Three scoops, hot fudge, nuts and a cherry.",
        price: 22,
        category: "desserts",
        isAvailable: true,
        isPopular: false,
        image: iceCreamSundaeImg,
    },
];
